[package]
name = "taurus-provider"
version.workspace = true
edition.workspace = true

[dependencies]
tucana = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
futures-lite = { workspace = true }
async-nats = { workspace = true }
prost = { workspace = true }
tonic = { workspace = true }
taurus-core = { workspace = true }
