name: Build packages

on:
  push:

jobs:
  taurus:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup rust
        run: rustup update --no-self-update stable
      - name: Build Taurus
        run: PATH=${{ runner.temp }}/proto/bin:$PATH cargo build
        env:
          RUST_BACKTRACE: 'full'
      - name: Run Tests
        run: cargo test